In [1]:
import sys
import numpy as np
import pandas as pd

In [2]:
sys.path.insert(0, "../src")

In [3]:
from process_CD import load_cd

In [4]:
df = load_cd()

In [5]:
df_avh = df['avh']
df_r56 = df['r56']

In [6]:
df_r56.groupby('label_binary', as_index=False).size()

   label_binary  size
0             0  5243
1             1  2109

In [7]:
df_avh.groupby('label_binary', as_index=False).size()

   label_binary  size
0             0  4254
1             1  1170

In [8]:
2109/(2109+5245)

0.28678270329072614

In [9]:
1170/(1170+4254)

0.2157079646017699

In [11]:
from nltk.tokenize import RegexpTokenizer

In [19]:
tokenizer = RegexpTokenizer(r'\w+')
df_avh['n_tokens'] = df_avh['text'].apply(lambda x: len(tokenizer.tokenize(x)))
df_avh['n_len'] = df_avh['text'].apply(lambda x: len(x))

In [20]:
df_avh

,Unnamed: 0,study_id,annotator_id,avh_id,sent_id,text,ND,DT,L,O,...,SB,AR,AI,message_fold,client_fold,label_binary,label,dfSource,n_tokens,n_len
0,0,1,0,u00001966@avh-20190731-1,S0,"I'm busy with my infusion, which means I have ...",1,0.0,0.0,0.0,...,0.0,0.0,0.0,1,2,0,0,avh,15,68
1,1,1,0,u00001966@avh-20190731-1,S1,No hearing voices then.,1,0.0,0.0,0.0,...,0.0,0.0,0.0,0,2,0,0,avh,4,23
2,2,1,0,u00001966@avh-20190731-1,S2,"When I got home and I was alone in my room, I ...",1,0.0,0.0,0.0,...,0.0,0.0,0.0,3,2,0,0,avh,15,60
3,3,1,0,u00001966@avh-20190731-1,S3,"Weirdly enough, the voice was male this time.",1,0.0,0.0,0.0,...,0.0,0.0,0.0,1,2,0,0,avh,8,45
4,4,2,0,u00001035@avh-20181105-1,S0,Okay.,1,0.0,0.0,0.0,...,0.0,0.0,0.0,0,2,0,0,avh,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5419,5419,510,2,u00001706@avh-20190325-1,S5,"Um, not like I would like it to.",1,0.0,0.0,0.0,...,0.0,0.0,0.0,0,3,0,0,avh,8,32
5420,5420,510,2,u00001706@avh-20190325-1,S6,"Um, it justit just doesn't work.",0,0.0,0.0,1.0,...,0.0,0.0,0.0,2,3,1,1,avh,7,32
5421,5421,511,2,u00002028@avh-20190719-1,S0,"So, my voices - it sounds so crazy when I'm sa...",0,0.0,0.0,0.0,...,0.0,0.0,1.0,0,2,1,1,avh,48,230
5422,5422,511,2,u00002028@avh-20190719-1,S1,"But like, it's mostly, like, a full blown out ...",1,0.0,0.0,0.0,...,0.0,0.0,0.0,0,2,0,0,avh,41,211
5423,5423,511,2,u00002028@avh-20190719-1,S2,"And it's like, if there was a person next to m...",1,0.0,0.0,0.0,...,0.0,0.0,0.0,3,2,0,0,avh,14,63

In [21]:
df_avh['n_tokens'].describe()

count    5424.000000
mean       14.491519
std        13.739775
min         0.000000
25%         6.000000
50%        10.000000
75%        19.000000
max       167.000000
Name: n_tokens, dtype: float64

In [22]:
df_avh['n_len'].describe()

count    5424.000000
mean       70.095317
std        68.214736
min         1.000000
25%        26.000000
50%        49.000000
75%        93.250000
max       848.000000
Name: n_len, dtype: float64