In [1]:
import sys
import numpy as np
import pandas as pd

In [2]:
sys.path.insert(0, "../src")

In [3]:
from process_CD import load_cd

In [4]:
df = load_cd()

In [5]:
df_avh = df['avh']
df_r56 = df['r56']

In [6]:
df_r56.groupby('label_binary', as_index=False).size()

   label_binary  size
0             0  5245
1             1  2109

In [7]:
df_avh.groupby('label_binary', as_index=False).size()

   label_binary  size
0             0  4254
1             1  1170

In [8]:
2109/(2109+5245)

0.28678270329072614

In [9]:
1170/(1170+4254)

0.2157079646017699